name: Compile userscript

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build
        run: python script/build.py
      - name: Set env
        run: |
          echo "VERSION=$(cat templates/version)" >> $GITHUB_ENV
          echo "LATEST_RELEASE_VERSION=${GITHUB_REF#refs/*/}" || echo "LATEST_RELEASE_VERSION=0.0" >> $GITHUB_ENV
          if [ "$VERSION" -gt "$LATEST_RELEASE_VERSION" ]; then
            echo "SHOULD_RELEASE=true" >> $GITHUB_ENV
          else
            echo "SHOULD_RELEASE=false" >> $GITHUB_ENV
          fi
      - name: Release
        if: ${{ env.SHOULD_RELEASE == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ASF-STM.user.js
          name: ASF-STM V${{ env.VERSION }} 
